pub(crate) const WASIP1_PREVIEW1_MODULE: &str = "wasi_snapshot_preview1";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Wasip1ImportName {
    ArgsGet,
    ArgsSizesGet,
    ClockResGet,
    ClockTimeGet,
    EnvironGet,
    EnvironSizesGet,
    FdAdvise,
    FdAllocate,
    FdClose,
    FdDatasync,
    FdFdstatGet,
    FdFdstatSetFlags,
    FdFdstatSetRights,
    FdFilestatGet,
    FdFilestatSetSize,
    FdFilestatSetTimes,
    FdPread,
    FdPrestatGet,
    FdPrestatDirName,
    FdPwrite,
    FdRead,
    FdReaddir,
    FdRenumber,
    FdSeek,
    FdSync,
    FdTell,
    FdWrite,
    PathCreateDirectory,
    PathFilestatGet,
    PathFilestatSetTimes,
    PathLink,
    PathOpen,
    PathReadlink,
    PathRemoveDirectory,
    PathRename,
    PathSymlink,
    PathUnlinkFile,
    PollOneoff,
    ProcExit,
    ProcRaise,
    RandomGet,
    SchedYield,
    SockAccept,
    SockRecv,
    SockSend,
    SockShutdown,
}

impl Wasip1ImportName {
    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::ArgsGet => "args_get",
            Self::ArgsSizesGet => "args_sizes_get",
            Self::ClockResGet => "clock_res_get",
            Self::ClockTimeGet => "clock_time_get",
            Self::EnvironGet => "environ_get",
            Self::EnvironSizesGet => "environ_sizes_get",
            Self::FdAdvise => "fd_advise",
            Self::FdAllocate => "fd_allocate",
            Self::FdClose => "fd_close",
            Self::FdDatasync => "fd_datasync",
            Self::FdFdstatGet => "fd_fdstat_get",
            Self::FdFdstatSetFlags => "fd_fdstat_set_flags",
            Self::FdFdstatSetRights => "fd_fdstat_set_rights",
            Self::FdFilestatGet => "fd_filestat_get",
            Self::FdFilestatSetSize => "fd_filestat_set_size",
            Self::FdFilestatSetTimes => "fd_filestat_set_times",
            Self::FdPread => "fd_pread",
            Self::FdPrestatGet => "fd_prestat_get",
            Self::FdPrestatDirName => "fd_prestat_dir_name",
            Self::FdPwrite => "fd_pwrite",
            Self::FdRead => "fd_read",
            Self::FdReaddir => "fd_readdir",
            Self::FdRenumber => "fd_renumber",
            Self::FdSeek => "fd_seek",
            Self::FdSync => "fd_sync",
            Self::FdTell => "fd_tell",
            Self::FdWrite => "fd_write",
            Self::PathCreateDirectory => "path_create_directory",
            Self::PathFilestatGet => "path_filestat_get",
            Self::PathFilestatSetTimes => "path_filestat_set_times",
            Self::PathLink => "path_link",
            Self::PathOpen => "path_open",
            Self::PathReadlink => "path_readlink",
            Self::PathRemoveDirectory => "path_remove_directory",
            Self::PathRename => "path_rename",
            Self::PathSymlink => "path_symlink",
            Self::PathUnlinkFile => "path_unlink_file",
            Self::PollOneoff => "poll_oneoff",
            Self::ProcExit => "proc_exit",
            Self::ProcRaise => "proc_raise",
            Self::RandomGet => "random_get",
            Self::SchedYield => "sched_yield",
            Self::SockAccept => "sock_accept",
            Self::SockRecv => "sock_recv",
            Self::SockSend => "sock_send",
            Self::SockShutdown => "sock_shutdown",
        }
    }

    pub(crate) fn from_bytes(bytes: &[u8]) -> Option<Self> {
        WASIP1_PREVIEW1_IMPORTS
            .iter()
            .copied()
            .find(|import| import.name().as_bytes() == bytes)
    }
}

pub(crate) const WASIP1_PREVIEW1_IMPORTS: [Wasip1ImportName; 46] = [
    Wasip1ImportName::ArgsGet,
    Wasip1ImportName::ArgsSizesGet,
    Wasip1ImportName::ClockResGet,
    Wasip1ImportName::ClockTimeGet,
    Wasip1ImportName::EnvironGet,
    Wasip1ImportName::EnvironSizesGet,
    Wasip1ImportName::FdAdvise,
    Wasip1ImportName::FdAllocate,
    Wasip1ImportName::FdClose,
    Wasip1ImportName::FdDatasync,
    Wasip1ImportName::FdFdstatGet,
    Wasip1ImportName::FdFdstatSetFlags,
    Wasip1ImportName::FdFdstatSetRights,
    Wasip1ImportName::FdFilestatGet,
    Wasip1ImportName::FdFilestatSetSize,
    Wasip1ImportName::FdFilestatSetTimes,
    Wasip1ImportName::FdPread,
    Wasip1ImportName::FdPrestatGet,
    Wasip1ImportName::FdPrestatDirName,
    Wasip1ImportName::FdPwrite,
    Wasip1ImportName::FdRead,
    Wasip1ImportName::FdReaddir,
    Wasip1ImportName::FdRenumber,
    Wasip1ImportName::FdSeek,
    Wasip1ImportName::FdSync,
    Wasip1ImportName::FdTell,
    Wasip1ImportName::FdWrite,
    Wasip1ImportName::PathCreateDirectory,
    Wasip1ImportName::PathFilestatGet,
    Wasip1ImportName::PathFilestatSetTimes,
    Wasip1ImportName::PathLink,
    Wasip1ImportName::PathOpen,
    Wasip1ImportName::PathReadlink,
    Wasip1ImportName::PathRemoveDirectory,
    Wasip1ImportName::PathRename,
    Wasip1ImportName::PathSymlink,
    Wasip1ImportName::PathUnlinkFile,
    Wasip1ImportName::PollOneoff,
    Wasip1ImportName::ProcExit,
    Wasip1ImportName::ProcRaise,
    Wasip1ImportName::RandomGet,
    Wasip1ImportName::SchedYield,
    Wasip1ImportName::SockAccept,
    Wasip1ImportName::SockRecv,
    Wasip1ImportName::SockSend,
    Wasip1ImportName::SockShutdown,
];
